include:
  - board: seeeduino_xiao_ble
    shield: kimiboard rgbled_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    after_script: |
      mv build/zephyr/kimiboard\ rgbled_adapter-seeeduino_xiao_ble-zmk.uf2 build/zephyr/kimiboard-seeeduino_xiao_ble-zmk.uf2
  - board: seeeduino_xiao_ble
    shield: settings_reset
